import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';
import './globals.css';

import Nav from './Nav';
import { useState } from 'react';

const inter = Nunito({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'countries Library',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={` ${inter.className} bg-light-forbg dark:bg-dark-forbg`}>
				<Nav />
				{children}
			</body>
		</html>
	);
}
